services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orion-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3005
    env_file:
      - .env
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
